# Copyright (c) 2025, Nitish Mashal and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document


class Expense(Document):
	# begin: auto-generated types
	# This section defines type hints for fields in the DocType for development support (used by language servers).
	# It is auto-generated by Frappe and should not be edited manually.

	from typing import TYPE_CHECKING

	if TYPE_CHECKING:
		from frappe.types import DF  # DF = Data Field (Frappe internal typing helper)
		from splitwise.splitwise.doctype.expense_split.expense_split import ExpenseSplit  # Linked child table DocType

		# Field type hints from the DocType
		amended_from: DF.Link | None                   # Link field, optionally points to another Expense
		amount: DF.Currency                            # Total amount of the expense
		currency: DF.Link                              # Currency used (linked to Currency doctype)
		date: DF.Date                                  # Date of the expense
		description: DF.Data                           # Description of the expense
		notes: DF.SmallText | None                     # Additional notes (optional)
		paid_by: DF.Link                               # Link to the user who paid the expense
		split_method: DF.Literal["Equally", "Manual"]  # Determines how the amount is split: Equally or Manual
		splits: DF.Table[ExpenseSplit]                 # Child table containing the split details (linked to ExpenseSplit)
	# end: auto-generated types

	# This method runs before the document is saved
	def before_save(self):
		self.apply_split()  # Call the logic to process splits based on the chosen method

	# Determines how to apply the split based on the chosen split method
	def apply_split(self):
		if self.split_method == "Equally":
			self.calculate_equal_split()  # Automatically divide the amount equally among all splits
		else:
			# Manual split: assumes that the user manually entered the split amounts
			pass

	# Logic to divide the expense equally among all split rows
	def calculate_equal_split(self):
		num_splits = len(self.splits)  # Count how many people/rows to split with
		if num_splits == 0:
			frappe.throw("At least one split is required.")  # Error if no splits defined

		split_amount = self.amount / num_splits  # Calculate equal share for each split

		for s in self.splits:
			s.amount = split_amount  # Assign the equal split amount to each row in the splits table
